# Site settings
title: Cleveland RailsBridge
email: info@clevelandrailsbridge.org
description: "Cleveland RailsBridge is an organization that works to increase diversity in tech by putting on a variety of awesome free events that help people get introduced to programming."
url: "http://clevelandrailsbridge.org"
base_url: /
twitter_username: clevelandrailsbridge
ga_account: UA-52875134-1

# Collections
collections:
 curriculum:
   output: true

# Build settings
markdown: kramdown
permalink: pretty
